env: dev
region: us-east-1
account: null

existingBucketName: www.backroombrewery.com

cloudfront:
  distributionId: E1F2ORA7T7DWNR
  domainName: d22fmn95qphprm.cloudfront.net

lambda:
  envVars:
    LOG_LEVEL: INFO
    STAGE: dev

holidayMarket:
  lambda:
    envVars:
      LOG_LEVEL: INFO
      STAGE: dev
